---
name: dummy

services:
  dbmate:
    container_name: dummy_dbmate
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    image: amacneil/dbmate:latest
    volumes:
      - ./db:/db
    depends_on:
      db:
        condition: service_healthy
    command: |
      --help

  db:
    container_name: dummy_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      interval: 10s
      retries: 5
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 5s
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data/

version: "3.8"

volumes:
  pgdata:
    driver: local
